# Generated by Django 2.2.10 on 2020-02-29 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='last_login',
        ),
    ]
