version: "3.3"
services:

  django:
    image: quack-api
    build:
      context: .
      args:
        release: dev
    volumes:
      - ./:/usr/src/app
      - django-media:/usr/src/app/media
      - django-static:/usr/src/app/static
    environment:
      - COMMAND=runserver
    ports:
      - 8000:8000
    depends_on:
      - postgres

  postgres:
    image: postgres:10
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/data
    environment:
      - POSTGRES_PASSWORD=postgres

volumes:
  django-media:
  django-static:
  postgres-data: